[package]
name = "victo/escape-island"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
fusion = "elttob/fusion@0.3.0"
knit = "sleitnick/knit@1.7.0"
goodsignal = "stravant/goodsignal@0.3.0"
ui-labs = "pepeeltoro41/ui-labs@2.3.8"
trove = "sleitnick/trove@1.5.0"
goodsignal = "l3g5nd/goodsignal@2.0.0"
matter = "matter-ecs/matter@0.8.4"
cmdr = "evaera/cmdr@1.12.0"

[server-dependencies]
profilestore = "vyon/profilestore@1.0.3"git push -u origin main
